title: ChainCeption
description: "A voyage through the ledger of trust, an attempt to unveil blockchain’s boundless promise through first principle."
baseurl: ""                   # root of domain
url: "https://chainception.github.io"
theme: minima
